services:
  tradexpress-platform:
    build:
      context: .
      dockerfile: Cloudboxfile
    container_name: kenwell-tx-unified-cluster
    restart: always
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - ./database.db:/usr/src/app/database.db
      - ./backups:/usr/src/app/backups
    environment:
      - NODE_ENV=production
      - SERVER_TARGET_HOST=192.168.100.11
